version: 2
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/decimalnonassign
    ldflags: -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^test:"
