name: test-lint

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - "1.19"
          - "1.20"
          - "1.22"
          - "1.23"
          - "1.24"
    steps:
      - name: set up go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: check out
        uses: actions/checkout@v4
      - name: build
        run: go build ./...
      - name: test
        run: go test ./... -v

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.64
